mirobot:
  arm_joint_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6

    # /gazebo_ros_control:
    #   pid_gains:
    #     joint1:
    #       p: 1000.0
    #       i: 0.0
    #       d: 0.1
    #     joint2:
    #       p: 1000.0
    #       i: 0.0
    #       d: 0.1
    #     joint3:
    #       p: 1000.0
    #       i: 0.0
    #       d: 0.1
    #     joint4:
    #       p: 1000.0
    #       i: 0.0
    #       d: 0.1
    #     joint5:
    #       p: 1000.0
    #       i: 0.0
    #       d: 0.1
    #     joint6:
    #       p: 1000.0
    #       i: 0.0
    #       d: 0.1

    # /mirobot/gazebo_ros_control:
    #   pid_gains:
    #     joint1:
    #       p: 1000.0
    #       i: 0.0
    #       d: 0.1
    #     joint2:
    #       p: 1000.0
    #       i: 0.0
    #       d: 0.1
    #     joint3:
    #       p: 1000.0
    #       i: 0.0
    #       d: 0.1
    #     joint4:
    #       p: 1000.0
    #       i: 0.0
    #       d: 0.1
    #     joint5:
    #       p: 1000.0
    #       i: 0.0
    #       d: 0.1
    #     joint6:
    #       p: 1000.0
    #       i: 0.0
    #       d: 0.1

    gains:
      joint1:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      joint2:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      joint3:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      joint4:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      joint5:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      joint6:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}

  gripper_controller:
    type: "position_controllers/JointTrajectoryController"
    # type: "velocity_controllers/JointTrajectoryController"
    # type: "FollowJointTrajectory"
    # type: "effort_controllers/GripperActionController"
    joints:
      - finger_joint
    # /gazebo_ros_control:
    #   pid_gains:
    #     finger_joint:
    #       p: 50.0
    #       i: 1.0
    #       d: 0.01
    #       i_clamp: 1.0
          
    # /mirobot/gazebo_ros_control:
    #   pid_gains:
    #     finger_joint:
    #       p: 50.0
    #       i: 1.0
    #       d: 0.01
          
    constraints :
      # stopped_position_tolerance: 0
      stopped_velocity_tolerance: 0.0
      finger_joint:
        goal: 1
    gains:
      # finger_joint:  {p: 10.0, d: 0.1, i: 1, i_clamp: 1.0}
      finger_joint:  {p: 1000.0, d: 0.1, i: 0.0, i_clamp: 0.0}

