mirobot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
    
  gripper_controller:
    # type: effort_controllers/GripperActionController
    type: joint_state_controller/JointStateController
    publish_rate: 50
    joint: finger_joint 
    gains:
      finger_joint: {p: 10,  d: 0.1, i: 1, i_clamp: 1}
    action_monitor_rate: 20
    goal_tolerance: 0.002
    max_effort: 50
    stall_velocity_threshold: 0.001
    stall_timeout: 1.0
    constraints :
      stopped_velocity_tolerance: 0
    
#   # gripper_state_controller:
#   #   # type: effort_controllers/GripperActionController
#   #   type: joint_state_controller/JointStateController
#   #   publish_rate: 50  
#   #   gains:
#   #     finger_joint: {p: 10,  d: 0.1, i: 1, i_clamp: 1}
#   #   joint: finger_joint 
#   #   action_monitor_rate: 20
#   #   goal_tolerance: 0.002
#   #   max_effort: 50
#   #   stall_velocity_threshold: 0.001
#   #   stall_timeout: 1.0

# mirobot:
#   # Publish all joint states -----------------------------------
#   joint_state_controller:
#     type: joint_state_controller/JointStateController
#     publish_rate: 50  
    
#   gripper_controller:
#     # type: effort_controllers/GripperActionController
#     type: joint_state_controller/JointStateController
#     gains:
#       finger_joint: {p: 10,  d: 0.1, i: 1, i_clamp: 1}
#     joint: finger_joint 
#     action_monitor_rate: 20
#     goal_tolerance: 0.002
#     max_effort: 50
#     stall_velocity_threshold: 0.001
#     stall_timeout: 1.0
